version: '3'

services: 
    node:
        build: .
        ports: 
            - "8000:8000"
    nginx:
        build: 
            context: ./nginx
        ports: 
            - "9000:80"
        links: 
            - "node"